org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#read more on this at https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Minecraft Related
neo_version=21.1.206
minecraft_version = 1.21.1
minecraft_sdk = neoforge

# Mod Version (for Local Builds Only)
semver = 999.999.999

# Curse Publishing Info
curse_project_id = 1412825

# Modrinth Publishing Info
modrinth_project_id = lhNCnNNS

# Dependency CurseForge Project IDs and File IDs (essentially the file id is synonymous with version number and archive classifier)
architectury_project_id = 419699
architectury_file_id = 5786327

# Dependency Version Info
jei_version = 19.22.1.316

modId=markdown_manual
mavenGroup=li.cil.markdown_manual

# Set by build pipeline.
modVersion=0.0.0
