modLoader = "javafml"
loaderVersion = "[20,)"
issueTrackerURL = "https://github.com/therealm18/MarkdownManual/issues"
license = "MIT"

[[mods]]
modId = "markdown_manual"
version = "${file.jarVersion}"
displayName = "Markdown Manual"
authors = "Sangar"
description = '''
Library mod providing a convenient way of defining in-game manuals.
'''

[[dependencies.markdown_manual]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.markdown_manual]]
modId = "minecraft"
type = "required"
versionRange = "1.20.4"
ordering = "NONE"
side = "BOTH"

[[dependencies.markdown_manual]]
modId = "architectury"
type = "required"
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
