modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/therealm18/MarkdownManual/issues"
license = "MIT"

[[mods]]
modId = "markdown_manual"
version = "${file.jarVersion}"
displayName = "Markdown Manual"
authors = "Mysticpasta1, Sangar"
description = '''
Library mod providing a convenient way of defining in-game manuals.
'''

[[dependencies.markdown_manual]]
modId = "neoforge"
type = "required"
versionRange = "[4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.markdown_manual]]
modId = "minecraft"
type = "required"
versionRange = "1.21.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.markdown_manual]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
