name: publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      mc_version: ${{ steps.split_tag.outputs.mc_version }}
      mod_version: ${{ steps.split_tag.outputs.mod_version }}

    steps:
      - name: Extract Version from Tag
        id: split_tag
        run: |
          tag=${{ github.event.release.tag_name }}
          parts=(${tag//\// })
          echo "mc_version=${parts[0]}" >> $GITHUB_OUTPUT
          echo "mod_version=${parts[1]}" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ubuntu-24.04-gradle-

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build with Gradle
        run: ./gradlew -PmodVersion='${{ steps.split_tag.outputs.mod_version }}' publish
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          RELEASE_TYPE: ${{ env.RELEASE_TYPE }}
          CHANGELOG: ${{ github.event.release.body }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Add Artifacts to Github Release
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./build/libs/*.jar"]'
