name: publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      mc_version: ${{ steps.extract_branch.outputs.branch }}
      mod_version: ${{ github.event.release.tag_name }}

    steps:
      - name: Extract branch name
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ubuntu-24.04-gradle-

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build with Gradle
        run: ./gradlew -Psemver='${{ github.event.release.tag_name }}' publish
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          RELEASE_TYPE: ${{ env.RELEASE_TYPE }}
          CHANGELOG: ${{ github.event.release.body }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Add Artifacts to Github Release
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./build/libs/*.jar"]'
